[package]
name = "buckram"
version = "0.0.1"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/merely-made/genet"
description = "Standards-owned CSS box and fragment models for Genet."

[lib]
path = "src/lib.rs"

[dependencies]
taffy = { version = "0.12.1", default-features = false, features = ["std", "block_layout", "float_layout", "flexbox", "grid", "calc"] }
